---
title: "Data Types"
author: "Arman"
date: '2022-02-23'
slug: data-types
categories: []
tags: []
---

## Cat Lovers
```{r}
library(tidyverse)
catlovers <- "https://raw.githubusercontent.com/dearbharat/tidyverse/main/cat-lovers.csv"

cat_lovers <- read_csv(catlovers)
```

### Summarize Data
```{r}
glimpse(cat_lovers)
cat_lovers %>%
  summarise(mean_cats = mean(number_of_cats, na.rm = TRUE))
```

### Fixing Bad Data
```{r}
cat_lovers %>%
  mutate(number_of_cats = case_when(
      name == "Ginger Clark" ~ 2,
      name == "Doug Bass"    ~ 3,
      TRUE                   ~ as.numeric(number_of_cats)
      )) %>%
  summarise(mean_cats = mean(number_of_cats))
```

### Numeric Data Summary
```{r}
cat_lovers %>%
  mutate(
    number_of_cats = case_when(
      name == "Ginger Clark" ~ "2",
      name == "Doug Bass"    ~ "3",
      TRUE                   ~ number_of_cats
      ),
    number_of_cats = as.numeric(number_of_cats)
    ) %>%
  summarise(mean_cats = mean(number_of_cats))
```

## Data Types - Coercion

```{r}
typeof(TRUE)
typeof("Hello!")
```

## Explicit Coercion

Number vs Character
```{r}
x <- 1:3
typeof(x)
typeof(as.character(x))
```

Number vs Logical
```{r}
x <- c(TRUE, FALSE)
typeof(x)
typeof(as.numeric(x))
```